temp/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Phone Screen</fullName>
                </value>
                <value>
                    <fullName>Schedule Interviews</fullName>
                </value>
                <value>
                    <fullName>Interviews Completed</fullName>
                </value>
                <value>
                    <fullName>Offer Extended</fullName>
                </value>
                <value>
                    <fullName>Closed - Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed - Accepted</fullName>
                </value>
                <value>
                    <fullName>Closed - Declined</fullName>
                </value>
                <value>
                    <fullName>Closed - Position Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Position__c.object
<CustomObject>
    <description>This object stores information about
the open job positions at our company</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataFactoryForTaskCreationTrigger.cls
public class TestDataFactoryForTaskCreationTrigger
{
    public static Integer positionsListSize;
    public static Integer candidatesListSize;
    public static List<Candidate__c> createCandids( Integer numberOfCandids)
    {
        List<Candidate__c> candidates = new List<Candidate__c>();
        for ( Integer i = 0 ; i < numberOfCandids ; i++ )
            {
                Candidate__c candidate = new Candidate__c( First_Name__c = 'Candidate' + i, City__c = 'NY');
                candidates.add(candidate);
            }
        insert candidates;
        candidatesListSize = numberOfCandids;
        return candidates;
    }
    public static List<Position__c> createPositions( Integer numberOfPositions )
    {
        List<Position__c> positions = new List<Position__c>();
        for ( Integer i = 0 ; i < numberOfPositions ; i++ )
            {
                Position__c position = new Position__c( Name = 'Position' + i);
                positions.add(position);
            }
        insert positions;
        positionsListSize = numberOfPositions;
        return positions;
    }
    public static List<Job_Application__c> createJobApps( Integer numberOfJobApps,List<Position__c> positions, List<Candidate__c> candidates )
    {
        List<Job_Application__c> jobApps = new List<Job_Application__c>();
        positions = createPositions(positionsListSize);
        candidates = createCandids(candidatesListSize);
        for ( Integer i = 0 ; i < numberOfJobApps ; i++ )
            {
                Position__c position = positions[0];
                Candidate__c candidate = candidates[0];
                Job_Application__c jobApp = new Job_Application__c(Stage__c='New',Status__c='Open',Position__c = position.Id, Candidate__c = candidate.id);
                jobApps.add(jobApp);
            }
        insert jobApps;
        return jobApps;
    }
}