temp/objects/Candidate__c.object
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Phone Screen</fullName>
                </value>
                <value>
                    <fullName>Schedule Interviews</fullName>
                </value>
                <value>
                    <fullName>Interviews Completed</fullName>
                </value>
                <value>
                    <fullName>Offer Extended</fullName>
                </value>
                <value>
                    <fullName>Closed - Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed - Accepted</fullName>
                </value>
                <value>
                    <fullName>Closed - Declined</fullName>
                </value>
                <value>
                    <fullName>Closed - Position Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/objects/Position__c.object
<CustomObject>
    <description>This object stores information about
the open job positions at our company</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateTaskOnJobAppTestClass.cls
@isTest
private class CreateTaskOnJobAppTestClass
{
    static testMethod void validateCreateTaskOnJobApp()
    {
        List<Position__c> positions = TestDataFactoryForTaskCreationTrigger.createPositions(1);
        List<Candidate__c> candidates = TestDataFactoryForTaskCreationTrigger.createCandids(1);
        List<Job_Application__c> jobApplications = TestDataFactoryForTaskCreationTrigger.createJobApps(2,positions, candidates);
        Job_Application__c jobApplication1 = jobApplications[0];
        jobApplication1.Stage__c = 'Closed - Rejected';
        jobApplication1.Status__c = 'Closed';
        Job_Application__c jobApplication2 = jobApplications[1];
        jobApplication2.Stage__c = 'Offer Extended';
        jobApplication2.Status__c = 'Hold';
        Test.startTest();
        update jobApplications;
        Test.stopTest();
        List<Task> tasksforRejected = new List<Task>([select id from Task where Subject like 'Send Rejection Letter']);
        List<Task> tasksforExtend = new List<Task>([select id from Task where Subject like 'Extend an Offer']);
        System.assertEquals(1, tasksforRejected.size());
     	System.assertEquals(1, tasksforExtend.size());
    }
    static testMethod void validateTaskNOTCreatedOnJobApp()
    {
        List<Position__c> positions = TestDataFactoryForTaskCreationTrigger.createPositions(1);
        List<Candidate__c> candidates = TestDataFactoryForTaskCreationTrigger.createCandids(1);
        List<Job_Application__c> jobApplications = TestDataFactoryForTaskCreationTrigger.createJobApps(1,positions, candidates);
        Job_Application__c jobApplication = jobApplications[0];
        jobApplication.Stage__c = 'Closed - Declined';
        jobApplication.Status__c = 'Closed';
        Test.startTest();
        update jobApplications;
        Test.stopTest();
        List<Task> tasksNotCreated = new List<Task>([select id from Task]);
        System.assertEquals(0, tasksNotCreated.size());
    }
}